version: '3.7'

services:

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - "3307:3306"
    volumes:
      - db-vol:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d/:ro
  website:
    container_name: php72
    build:
      context: ./
    links:
      - "db:database"
    volumes:
      - ./app:/var/www/html
      
    ports:
      - 80:80
    depends_on:
      - db
      

volumes:
  db-vol: